source "https://rubygems.org"

gem "fastlane", "2.128.1"
gem "cocoapods", "1.7.5"
gem "xcpretty", "0.3.0"
gem "xcodeproj", "1.12.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
